# Generated by Django 3.0.6 on 2020-06-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Gallery'),
        ),
    ]
