# Generated by Django 3.0.8 on 2020-07-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200718_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='credit',
            field=models.TextField(blank=True),
        ),
    ]
