# Generated by Django 3.0.8 on 2020-07-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_photo_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='credit',
        ),
    ]
