# Generated by Django 3.0.8 on 2020-07-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_photo_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='credit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
